// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220321185803_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Domain.Entities.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Joined")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Team")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("Player");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            Joined = new DateTime(2022, 3, 21, 11, 58, 2, 632, DateTimeKind.Local).AddTicks(7110),
                            Name = "Trae Young",
                            PhotoPath = "/Photos/nba_anonymous.jpg",
                            Team = "Hawks"
                        },
                        new
                        {
                            PlayerId = 2,
                            Joined = new DateTime(2022, 3, 21, 11, 58, 2, 633, DateTimeKind.Local).AddTicks(80),
                            Name = "Jayson Tatum",
                            PhotoPath = "/Photos/nba_anonymous.jpg",
                            Team = "Celtics"
                        },
                        new
                        {
                            PlayerId = 3,
                            Joined = new DateTime(2022, 3, 21, 11, 58, 2, 633, DateTimeKind.Local).AddTicks(720),
                            Name = "Kevin Durant",
                            PhotoPath = "/Photos/nba_anonymous.jpg",
                            Team = "Nets"
                        },
                        new
                        {
                            PlayerId = 4,
                            Joined = new DateTime(2022, 3, 21, 11, 58, 2, 633, DateTimeKind.Local).AddTicks(830),
                            Name = "Stephen Curry",
                            PhotoPath = "/Photos/nba_anonymous.jpg",
                            Team = "Warriors"
                        },
                        new
                        {
                            PlayerId = 5,
                            Joined = new DateTime(2022, 3, 21, 11, 58, 2, 633, DateTimeKind.Local).AddTicks(850),
                            Name = "Zach LaVine",
                            PhotoPath = "/Photos/nba_anonymous.jpg",
                            Team = "Bulls"
                        },
                        new
                        {
                            PlayerId = 6,
                            Joined = new DateTime(2022, 3, 21, 11, 58, 2, 633, DateTimeKind.Local).AddTicks(860),
                            Name = "LeBron James",
                            PhotoPath = "/Photos/nba_anonymous.jpg",
                            Team = "Lakers"
                        },
                        new
                        {
                            PlayerId = 7,
                            Joined = new DateTime(2022, 3, 21, 11, 58, 2, 633, DateTimeKind.Local).AddTicks(870),
                            Name = "Anthony Davis",
                            PhotoPath = "/Photos/nba_anonymous.jpg",
                            Team = "Lakers"
                        },
                        new
                        {
                            PlayerId = 8,
                            Joined = new DateTime(2022, 3, 21, 11, 58, 2, 633, DateTimeKind.Local).AddTicks(890),
                            Name = "Julius Randle",
                            PhotoPath = "/Photos/nba_anonymous.jpg",
                            Team = "Knicks"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Arena")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateFounded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("TEXT");

                    b.HasKey("TeamId");

                    b.ToTable("Team");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            City = "Atlanta",
                            DateFounded = new DateTime(2022, 3, 21, 11, 58, 2, 600, DateTimeKind.Local).AddTicks(110),
                            Name = "Hawks",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 2,
                            City = "Boston",
                            DateFounded = new DateTime(2022, 3, 21, 11, 58, 2, 629, DateTimeKind.Local).AddTicks(7330),
                            Name = "Celtics",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 3,
                            City = "Brooklyn",
                            DateFounded = new DateTime(2022, 3, 21, 11, 58, 2, 629, DateTimeKind.Local).AddTicks(8880),
                            Name = "Nets",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 4,
                            City = "Charlotte",
                            DateFounded = new DateTime(2022, 3, 21, 11, 58, 2, 629, DateTimeKind.Local).AddTicks(8990),
                            Name = "Hornets",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 5,
                            City = "Chicago",
                            DateFounded = new DateTime(2022, 3, 21, 11, 58, 2, 630, DateTimeKind.Local).AddTicks(590),
                            Name = "Bulls",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 6,
                            City = "Cleveland",
                            DateFounded = new DateTime(2022, 3, 21, 11, 58, 2, 630, DateTimeKind.Local).AddTicks(610),
                            Name = "Cavaliers",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 7,
                            City = "Dallas",
                            DateFounded = new DateTime(2022, 3, 21, 11, 58, 2, 630, DateTimeKind.Local).AddTicks(620),
                            Name = "Mavericks",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 8,
                            City = "Denver",
                            DateFounded = new DateTime(2022, 3, 21, 11, 58, 2, 630, DateTimeKind.Local).AddTicks(640),
                            Name = "Nuggets",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 9,
                            City = "Detroit",
                            DateFounded = new DateTime(2022, 3, 21, 11, 58, 2, 630, DateTimeKind.Local).AddTicks(650),
                            Name = "Pistons",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 10,
                            City = "Golden State",
                            DateFounded = new DateTime(2022, 3, 21, 11, 58, 2, 630, DateTimeKind.Local).AddTicks(660),
                            Name = "Warriors",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 11,
                            City = "Houston",
                            DateFounded = new DateTime(2022, 3, 21, 11, 58, 2, 630, DateTimeKind.Local).AddTicks(670),
                            Name = "Rockets",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 12,
                            City = "Indiana",
                            DateFounded = new DateTime(2022, 3, 21, 11, 58, 2, 630, DateTimeKind.Local).AddTicks(690),
                            Name = "Pacers",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 13,
                            City = "Los Angeles",
                            DateFounded = new DateTime(2022, 3, 21, 11, 58, 2, 630, DateTimeKind.Local).AddTicks(700),
                            Name = "Clippers",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 14,
                            City = "Los Angeles",
                            DateFounded = new DateTime(2022, 3, 21, 11, 58, 2, 630, DateTimeKind.Local).AddTicks(730),
                            Name = "Lakers",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 15,
                            City = "Memphis",
                            DateFounded = new DateTime(2022, 3, 21, 11, 58, 2, 630, DateTimeKind.Local).AddTicks(740),
                            Name = "Grizzlies",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 16,
                            City = "Miami",
                            DateFounded = new DateTime(2022, 3, 21, 11, 58, 2, 630, DateTimeKind.Local).AddTicks(750),
                            Name = "Heat",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 17,
                            City = "Milwaukee",
                            DateFounded = new DateTime(2022, 3, 21, 11, 58, 2, 630, DateTimeKind.Local).AddTicks(770),
                            Name = "Bucks",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 18,
                            City = "Minnesota",
                            DateFounded = new DateTime(2022, 3, 21, 11, 58, 2, 630, DateTimeKind.Local).AddTicks(780),
                            Name = "Timberwolves",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 19,
                            City = "New Orleans",
                            DateFounded = new DateTime(2022, 3, 21, 11, 58, 2, 630, DateTimeKind.Local).AddTicks(790),
                            Name = "Pelicans",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 20,
                            City = "New York",
                            DateFounded = new DateTime(2022, 3, 21, 11, 58, 2, 630, DateTimeKind.Local).AddTicks(800),
                            Name = "Knicks",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 21,
                            City = "Oklahoma City",
                            DateFounded = new DateTime(2022, 3, 21, 11, 58, 2, 630, DateTimeKind.Local).AddTicks(810),
                            Name = "Thunder",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 22,
                            City = "Orlando",
                            DateFounded = new DateTime(2022, 3, 21, 11, 58, 2, 630, DateTimeKind.Local).AddTicks(820),
                            Name = "Magic",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 23,
                            City = "Philadelphia",
                            DateFounded = new DateTime(2022, 3, 21, 11, 58, 2, 630, DateTimeKind.Local).AddTicks(840),
                            Name = "76ers",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 24,
                            City = "Phoenix",
                            DateFounded = new DateTime(2022, 3, 21, 11, 58, 2, 630, DateTimeKind.Local).AddTicks(850),
                            Name = "Suns",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 25,
                            City = "Portland",
                            DateFounded = new DateTime(2022, 3, 21, 11, 58, 2, 630, DateTimeKind.Local).AddTicks(2480),
                            Name = "Trail Blazers",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 26,
                            City = "Sacramento",
                            DateFounded = new DateTime(2022, 3, 21, 11, 58, 2, 630, DateTimeKind.Local).AddTicks(2500),
                            Name = "Kings",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 27,
                            City = "San Antonio",
                            DateFounded = new DateTime(2022, 3, 21, 11, 58, 2, 630, DateTimeKind.Local).AddTicks(2510),
                            Name = "Spurs",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 28,
                            City = "Toronto",
                            DateFounded = new DateTime(2022, 3, 21, 11, 58, 2, 630, DateTimeKind.Local).AddTicks(2520),
                            Name = "Raptos",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 29,
                            City = "Utah",
                            DateFounded = new DateTime(2022, 3, 21, 11, 58, 2, 630, DateTimeKind.Local).AddTicks(2540),
                            Name = "Jazz",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 30,
                            City = "Washington",
                            DateFounded = new DateTime(2022, 3, 21, 11, 58, 2, 630, DateTimeKind.Local).AddTicks(2550),
                            Name = "Wizards",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        });
                });

            modelBuilder.Entity("Domain.Entities.TeamHistory", b =>
                {
                    b.Property<int>("TeamHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DEFGPct")
                        .HasColumnType("REAL");

                    b.Property<double>("DRB")
                        .HasColumnType("REAL");

                    b.Property<double>("DRTg")
                        .HasColumnType("REAL");

                    b.Property<double>("FTr")
                        .HasColumnType("REAL");

                    b.Property<int>("LossRecord")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MOV")
                        .HasColumnType("REAL");

                    b.Property<double>("NRTg")
                        .HasColumnType("REAL");

                    b.Property<double>("OEFGPct")
                        .HasColumnType("REAL");

                    b.Property<double>("ORB")
                        .HasColumnType("REAL");

                    b.Property<double>("ORTg")
                        .HasColumnType("REAL");

                    b.Property<double>("SOS")
                        .HasColumnType("REAL");

                    b.Property<string>("Season")
                        .HasColumnType("TEXT");

                    b.Property<string>("Team")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ThreePAr")
                        .HasColumnType("REAL");

                    b.Property<int>("WinRecord")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeamHistoryId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamHistory");

                    b.HasData(
                        new
                        {
                            TeamHistoryId = 1,
                            DEFGPct = 0.51500000000000001,
                            DRB = 78.799999999999997,
                            DRTg = 106.3,
                            FTr = 0.27600000000000002,
                            LossRecord = 19,
                            MOV = 5.79,
                            NRTg = 0.0,
                            OEFGPct = 0.54200000000000004,
                            ORB = 24.5,
                            ORTg = 112.0,
                            SOS = 0.48999999999999999,
                            Season = "2019-2020",
                            Team = "Lakers",
                            ThreePAr = 0.35799999999999998,
                            WinRecord = 52
                        },
                        new
                        {
                            TeamHistoryId = 2,
                            DEFGPct = 0.52300000000000002,
                            DRB = 79.5,
                            DRTg = 109.5,
                            FTr = 0.29899999999999999,
                            LossRecord = 29,
                            MOV = 2.9500000000000002,
                            NRTg = 0.0,
                            OEFGPct = 0.54700000000000004,
                            ORB = 20.300000000000001,
                            ORTg = 112.5,
                            SOS = 0.34999999999999998,
                            Season = "2019-2020",
                            Team = "Heat",
                            ThreePAr = 0.41899999999999998,
                            WinRecord = 44
                        });
                });

            modelBuilder.Entity("Domain.Entities.Player", b =>
                {
                    b.HasOne("Domain.Entities.Team", null)
                        .WithMany("Players")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("Domain.Entities.TeamHistory", b =>
                {
                    b.HasOne("Domain.Entities.Team", null)
                        .WithMany("TeamHistories")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("Domain.Entities.Team", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("TeamHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
