// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Domain.Entities.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Joined")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Team")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("Player");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            Joined = new DateTime(2022, 4, 12, 1, 5, 53, 166, DateTimeKind.Local).AddTicks(5220),
                            Name = "Trae Young",
                            PhotoPath = "/Photos/nba_anonymous.jpg",
                            Team = "Hawks"
                        },
                        new
                        {
                            PlayerId = 2,
                            Joined = new DateTime(2022, 4, 12, 1, 5, 53, 166, DateTimeKind.Local).AddTicks(8270),
                            Name = "Jayson Tatum",
                            PhotoPath = "/Photos/nba_anonymous.jpg",
                            Team = "Celtics"
                        },
                        new
                        {
                            PlayerId = 3,
                            Joined = new DateTime(2022, 4, 12, 1, 5, 53, 166, DateTimeKind.Local).AddTicks(8860),
                            Name = "Kevin Durant",
                            PhotoPath = "/Photos/nba_anonymous.jpg",
                            Team = "Nets"
                        },
                        new
                        {
                            PlayerId = 4,
                            Joined = new DateTime(2022, 4, 12, 1, 5, 53, 166, DateTimeKind.Local).AddTicks(8930),
                            Name = "Stephen Curry",
                            PhotoPath = "/Photos/nba_anonymous.jpg",
                            Team = "Warriors"
                        },
                        new
                        {
                            PlayerId = 5,
                            Joined = new DateTime(2022, 4, 12, 1, 5, 53, 166, DateTimeKind.Local).AddTicks(8950),
                            Name = "Zach LaVine",
                            PhotoPath = "/Photos/nba_anonymous.jpg",
                            Team = "Bulls"
                        },
                        new
                        {
                            PlayerId = 6,
                            Joined = new DateTime(2022, 4, 12, 1, 5, 53, 166, DateTimeKind.Local).AddTicks(8960),
                            Name = "LeBron James",
                            PhotoPath = "/Photos/nba_anonymous.jpg",
                            Team = "Lakers"
                        },
                        new
                        {
                            PlayerId = 7,
                            Joined = new DateTime(2022, 4, 12, 1, 5, 53, 166, DateTimeKind.Local).AddTicks(8970),
                            Name = "Anthony Davis",
                            PhotoPath = "/Photos/nba_anonymous.jpg",
                            Team = "Lakers"
                        },
                        new
                        {
                            PlayerId = 8,
                            Joined = new DateTime(2022, 4, 12, 1, 5, 53, 166, DateTimeKind.Local).AddTicks(8990),
                            Name = "Julius Randle",
                            PhotoPath = "/Photos/nba_anonymous.jpg",
                            Team = "Knicks"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Arena")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateFounded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("TEXT");

                    b.HasKey("TeamId");

                    b.ToTable("Team");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            City = "Atlanta",
                            DateFounded = new DateTime(2022, 4, 12, 1, 5, 53, 143, DateTimeKind.Local).AddTicks(5190),
                            Name = "Hawks",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 2,
                            City = "Boston",
                            DateFounded = new DateTime(2022, 4, 12, 1, 5, 53, 164, DateTimeKind.Local).AddTicks(2000),
                            Name = "Celtics",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 3,
                            City = "Brooklyn",
                            DateFounded = new DateTime(2022, 4, 12, 1, 5, 53, 164, DateTimeKind.Local).AddTicks(3120),
                            Name = "Nets",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 4,
                            City = "Charlotte",
                            DateFounded = new DateTime(2022, 4, 12, 1, 5, 53, 164, DateTimeKind.Local).AddTicks(3200),
                            Name = "Hornets",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 5,
                            City = "Chicago",
                            DateFounded = new DateTime(2022, 4, 12, 1, 5, 53, 164, DateTimeKind.Local).AddTicks(3220),
                            Name = "Bulls",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 6,
                            City = "Cleveland",
                            DateFounded = new DateTime(2022, 4, 12, 1, 5, 53, 164, DateTimeKind.Local).AddTicks(3230),
                            Name = "Cavaliers",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 7,
                            City = "Dallas",
                            DateFounded = new DateTime(2022, 4, 12, 1, 5, 53, 164, DateTimeKind.Local).AddTicks(3240),
                            Name = "Mavericks",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 8,
                            City = "Denver",
                            DateFounded = new DateTime(2022, 4, 12, 1, 5, 53, 164, DateTimeKind.Local).AddTicks(3250),
                            Name = "Nuggets",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 9,
                            City = "Detroit",
                            DateFounded = new DateTime(2022, 4, 12, 1, 5, 53, 164, DateTimeKind.Local).AddTicks(3270),
                            Name = "Pistons",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 10,
                            City = "Golden State",
                            DateFounded = new DateTime(2022, 4, 12, 1, 5, 53, 164, DateTimeKind.Local).AddTicks(3280),
                            Name = "Warriors",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 11,
                            City = "Houston",
                            DateFounded = new DateTime(2022, 4, 12, 1, 5, 53, 164, DateTimeKind.Local).AddTicks(3300),
                            Name = "Rockets",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 12,
                            City = "Indiana",
                            DateFounded = new DateTime(2022, 4, 12, 1, 5, 53, 164, DateTimeKind.Local).AddTicks(4790),
                            Name = "Pacers",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 13,
                            City = "Los Angeles",
                            DateFounded = new DateTime(2022, 4, 12, 1, 5, 53, 164, DateTimeKind.Local).AddTicks(4810),
                            Name = "Clippers",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 14,
                            City = "Los Angeles",
                            DateFounded = new DateTime(2022, 4, 12, 1, 5, 53, 164, DateTimeKind.Local).AddTicks(4820),
                            Name = "Lakers",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 15,
                            City = "Memphis",
                            DateFounded = new DateTime(2022, 4, 12, 1, 5, 53, 164, DateTimeKind.Local).AddTicks(4830),
                            Name = "Grizzlies",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 16,
                            City = "Miami",
                            DateFounded = new DateTime(2022, 4, 12, 1, 5, 53, 164, DateTimeKind.Local).AddTicks(4840),
                            Name = "Heat",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 17,
                            City = "Milwaukee",
                            DateFounded = new DateTime(2022, 4, 12, 1, 5, 53, 164, DateTimeKind.Local).AddTicks(4860),
                            Name = "Bucks",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 18,
                            City = "Minnesota",
                            DateFounded = new DateTime(2022, 4, 12, 1, 5, 53, 164, DateTimeKind.Local).AddTicks(4870),
                            Name = "Timberwolves",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 19,
                            City = "New Orleans",
                            DateFounded = new DateTime(2022, 4, 12, 1, 5, 53, 164, DateTimeKind.Local).AddTicks(4880),
                            Name = "Pelicans",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 20,
                            City = "New York",
                            DateFounded = new DateTime(2022, 4, 12, 1, 5, 53, 164, DateTimeKind.Local).AddTicks(4890),
                            Name = "Knicks",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 21,
                            City = "Oklahoma City",
                            DateFounded = new DateTime(2022, 4, 12, 1, 5, 53, 164, DateTimeKind.Local).AddTicks(4900),
                            Name = "Thunder",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 22,
                            City = "Orlando",
                            DateFounded = new DateTime(2022, 4, 12, 1, 5, 53, 164, DateTimeKind.Local).AddTicks(4920),
                            Name = "Magic",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 23,
                            City = "Philadelphia",
                            DateFounded = new DateTime(2022, 4, 12, 1, 5, 53, 164, DateTimeKind.Local).AddTicks(4930),
                            Name = "76ers",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 24,
                            City = "Phoenix",
                            DateFounded = new DateTime(2022, 4, 12, 1, 5, 53, 164, DateTimeKind.Local).AddTicks(4940),
                            Name = "Suns",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 25,
                            City = "Portland",
                            DateFounded = new DateTime(2022, 4, 12, 1, 5, 53, 164, DateTimeKind.Local).AddTicks(4950),
                            Name = "Trail Blazers",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 26,
                            City = "Sacramento",
                            DateFounded = new DateTime(2022, 4, 12, 1, 5, 53, 164, DateTimeKind.Local).AddTicks(4960),
                            Name = "Kings",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 27,
                            City = "San Antonio",
                            DateFounded = new DateTime(2022, 4, 12, 1, 5, 53, 164, DateTimeKind.Local).AddTicks(4970),
                            Name = "Spurs",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 28,
                            City = "Toronto",
                            DateFounded = new DateTime(2022, 4, 12, 1, 5, 53, 164, DateTimeKind.Local).AddTicks(4990),
                            Name = "Raptos",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 29,
                            City = "Utah",
                            DateFounded = new DateTime(2022, 4, 12, 1, 5, 53, 164, DateTimeKind.Local).AddTicks(5000),
                            Name = "Jazz",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 30,
                            City = "Washington",
                            DateFounded = new DateTime(2022, 4, 12, 1, 5, 53, 164, DateTimeKind.Local).AddTicks(5010),
                            Name = "Wizards",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        });
                });

            modelBuilder.Entity("Domain.Entities.TeamHistory", b =>
                {
                    b.Property<int>("TeamHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DEFGPct")
                        .HasColumnType("REAL");

                    b.Property<double>("DRB")
                        .HasColumnType("REAL");

                    b.Property<double>("DRTg")
                        .HasColumnType("REAL");

                    b.Property<double>("FTr")
                        .HasColumnType("REAL");

                    b.Property<int>("LossRecord")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MOV")
                        .HasColumnType("REAL");

                    b.Property<double>("NRTg")
                        .HasColumnType("REAL");

                    b.Property<double>("OEFGPct")
                        .HasColumnType("REAL");

                    b.Property<double>("ORB")
                        .HasColumnType("REAL");

                    b.Property<double>("ORTg")
                        .HasColumnType("REAL");

                    b.Property<double>("SOS")
                        .HasColumnType("REAL");

                    b.Property<string>("Season")
                        .HasColumnType("TEXT");

                    b.Property<string>("Team")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ThreePAr")
                        .HasColumnType("REAL");

                    b.Property<int>("WinRecord")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeamHistoryId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamHistory");

                    b.HasData(
                        new
                        {
                            TeamHistoryId = 1,
                            DEFGPct = 0.503,
                            DRB = 0.0,
                            DRTg = 105.2,
                            FTr = 0.255,
                            LossRecord = 22,
                            MOV = 8.8699999999999992,
                            NRTg = 0.0,
                            OEFGPct = 0.55000000000000004,
                            ORB = 20.800000000000001,
                            ORTg = 113.8,
                            SOS = -0.81999999999999995,
                            Season = "2018-2019",
                            Team = "Bucks",
                            ThreePAr = 0.41899999999999998,
                            WinRecord = 60
                        },
                        new
                        {
                            TeamHistoryId = 2,
                            DEFGPct = 0.50800000000000001,
                            DRB = 0.0,
                            DRTg = 109.5,
                            FTr = 0.22700000000000001,
                            LossRecord = 25,
                            MOV = 6.46,
                            NRTg = 0.0,
                            OEFGPct = 0.56499999999999995,
                            ORB = 22.5,
                            ORTg = 115.90000000000001,
                            SOS = -0.040000000000000001,
                            Season = "2018-2019",
                            Team = "Warriors",
                            ThreePAr = 0.38400000000000001,
                            WinRecord = 57
                        },
                        new
                        {
                            TeamHistoryId = 3,
                            DEFGPct = 0.50900000000000001,
                            DRB = 0.0,
                            DRTg = 107.09999999999999,
                            FTr = 0.247,
                            LossRecord = 24,
                            MOV = 6.0899999999999999,
                            NRTg = 0.0,
                            OEFGPct = 0.54300000000000004,
                            ORB = 21.899999999999999,
                            ORTg = 113.09999999999999,
                            SOS = -0.59999999999999998,
                            Season = "2018-2019",
                            Team = "Raptors",
                            ThreePAr = 0.379,
                            WinRecord = 58
                        },
                        new
                        {
                            TeamHistoryId = 4,
                            DEFGPct = 0.50700000000000001,
                            DRB = 0.0,
                            DRTg = 105.7,
                            FTr = 0.29499999999999998,
                            LossRecord = 32,
                            MOV = 5.2599999999999998,
                            NRTg = 0.0,
                            OEFGPct = 0.53800000000000003,
                            ORB = 22.899999999999999,
                            ORTg = 110.90000000000001,
                            SOS = 0.029999999999999999,
                            Season = "2018-2019",
                            Team = "Jazz",
                            ThreePAr = 0.39400000000000002,
                            WinRecord = 50
                        },
                        new
                        {
                            TeamHistoryId = 5,
                            DEFGPct = 0.52500000000000002,
                            DRB = 0.0,
                            DRTg = 110.7,
                            FTr = 0.27900000000000003,
                            LossRecord = 29,
                            MOV = 4.7699999999999996,
                            NRTg = 0.0,
                            OEFGPct = 0.54200000000000004,
                            ORB = 22.800000000000001,
                            ORTg = 115.5,
                            SOS = 0.19,
                            Season = "2018-2019",
                            Team = "Rockets",
                            ThreePAr = 0.51900000000000002,
                            WinRecord = 53
                        },
                        new
                        {
                            TeamHistoryId = 6,
                            DEFGPct = 0.51400000000000001,
                            DRB = 0.0,
                            DRTg = 107.8,
                            FTr = 0.215,
                            LossRecord = 33,
                            MOV = 4.4400000000000004,
                            NRTg = 0.0,
                            OEFGPct = 0.53400000000000003,
                            ORB = 21.600000000000001,
                            ORTg = 112.2,
                            SOS = -0.54000000000000004,
                            Season = "2018-2019",
                            Team = "Celtics",
                            ThreePAr = 0.38100000000000001,
                            WinRecord = 49
                        },
                        new
                        {
                            TeamHistoryId = 7,
                            DEFGPct = 0.51600000000000001,
                            DRB = 0.0,
                            DRTg = 110.5,
                            FTr = 0.25800000000000001,
                            LossRecord = 29,
                            MOV = 4.2000000000000002,
                            NRTg = 0.0,
                            OEFGPct = 0.52800000000000002,
                            ORB = 26.600000000000001,
                            ORTg = 114.7,
                            SOS = 0.23999999999999999,
                            Season = "2018-2019",
                            Team = "Trail Blazers",
                            ThreePAr = 0.33900000000000002,
                            WinRecord = 53
                        },
                        new
                        {
                            TeamHistoryId = 8,
                            DEFGPct = 0.52100000000000002,
                            DRB = 0.0,
                            DRTg = 108.90000000000001,
                            FTr = 0.23200000000000001,
                            LossRecord = 28,
                            MOV = 3.9500000000000002,
                            NRTg = 0.0,
                            OEFGPct = 0.52700000000000002,
                            ORB = 26.600000000000001,
                            ORTg = 113.0,
                            SOS = 0.23999999999999999,
                            Season = "2018-2019",
                            Team = "Nuggets",
                            ThreePAr = 0.34799999999999998,
                            WinRecord = 54
                        },
                        new
                        {
                            TeamHistoryId = 9,
                            DEFGPct = 0.51600000000000001,
                            DRB = 0.0,
                            DRTg = 106.5,
                            FTr = 0.24199999999999999,
                            LossRecord = 34,
                            MOV = 3.3300000000000001,
                            NRTg = 0.0,
                            OEFGPct = 0.53000000000000003,
                            ORB = 21.899999999999999,
                            ORTg = 109.90000000000001,
                            SOS = -0.56999999999999995,
                            Season = "2018-2019",
                            Team = "Pacers",
                            ThreePAr = 0.29199999999999998,
                            WinRecord = 48
                        },
                        new
                        {
                            TeamHistoryId = 10,
                            DEFGPct = 0.52300000000000002,
                            DRB = 0.0,
                            DRTg = 107.0,
                            FTr = 0.26600000000000001,
                            LossRecord = 33,
                            MOV = 3.3999999999999999,
                            NRTg = 0.0,
                            OEFGPct = 0.51400000000000001,
                            ORB = 26.0,
                            ORTg = 110.3,
                            SOS = 0.14999999999999999,
                            Season = "2018-2019",
                            Team = "Thunder",
                            ThreePAr = 0.34699999999999998,
                            WinRecord = 49
                        },
                        new
                        {
                            TeamHistoryId = 11,
                            DEFGPct = 0.51200000000000001,
                            DRB = 0.0,
                            DRTg = 110.0,
                            FTr = 0.312,
                            LossRecord = 31,
                            MOV = 2.7000000000000002,
                            NRTg = 0.0,
                            OEFGPct = 0.53200000000000003,
                            ORB = 24.5,
                            ORTg = 112.59999999999999,
                            SOS = -0.44,
                            Season = "2018-2019",
                            Team = "76ers",
                            ThreePAr = 0.34200000000000003,
                            WinRecord = 51
                        },
                        new
                        {
                            TeamHistoryId = 12,
                            DEFGPct = 0.52800000000000002,
                            DRB = 0.0,
                            DRTg = 111.2,
                            FTr = 0.23699999999999999,
                            LossRecord = 34,
                            MOV = 1.6799999999999999,
                            NRTg = 0.0,
                            OEFGPct = 0.53400000000000003,
                            ORB = 21.0,
                            ORTg = 112.90000000000001,
                            SOS = 0.12,
                            Season = "2018-2019",
                            Team = "Spurs",
                            ThreePAr = 0.28599999999999998,
                            WinRecord = 48
                        },
                        new
                        {
                            TeamHistoryId = 13,
                            DEFGPct = 0.51400000000000001,
                            DRB = 0.0,
                            DRTg = 111.5,
                            FTr = 0.32600000000000001,
                            LossRecord = 34,
                            MOV = 0.84999999999999998,
                            NRTg = 0.0,
                            OEFGPct = 0.52900000000000003,
                            ORB = 22.0,
                            ORTg = 112.40000000000001,
                            SOS = 0.23000000000000001,
                            Season = "2018-2019",
                            Team = "Clippers",
                            ThreePAr = 0.29499999999999998,
                            WinRecord = 48
                        },
                        new
                        {
                            TeamHistoryId = 14,
                            DEFGPct = 0.51500000000000001,
                            DRB = 0.0,
                            DRTg = 108.09999999999999,
                            FTr = 0.216,
                            LossRecord = 40,
                            MOV = 0.70999999999999996,
                            NRTg = 0.0,
                            OEFGPct = 0.51800000000000002,
                            ORB = 22.0,
                            ORTg = 108.90000000000001,
                            SOS = -0.42999999999999999,
                            Season = "2018-2019",
                            Team = "Magic",
                            ThreePAr = 0.35999999999999999,
                            WinRecord = 42
                        },
                        new
                        {
                            TeamHistoryId = 15,
                            DEFGPct = 0.51200000000000001,
                            DRB = 0.0,
                            DRTg = 109.7,
                            FTr = 0.28399999999999997,
                            LossRecord = 40,
                            MOV = -0.070000000000000007,
                            NRTg = 0.0,
                            OEFGPct = 0.52000000000000002,
                            ORB = 23.800000000000001,
                            ORTg = 109.59999999999999,
                            SOS = -0.33000000000000002,
                            Season = "2018-2019",
                            Team = "Nets",
                            ThreePAr = 0.40300000000000002,
                            WinRecord = 42
                        },
                        new
                        {
                            TeamHistoryId = 16,
                            DEFGPct = 0.52600000000000002,
                            DRB = 0.0,
                            DRTg = 109.2,
                            FTr = 0.26200000000000001,
                            LossRecord = 41,
                            MOV = -0.23999999999999999,
                            NRTg = 0.0,
                            OEFGPct = 0.50900000000000001,
                            ORB = 24.800000000000001,
                            ORTg = 109.0,
                            SOS = -0.31,
                            Season = "2018-2019",
                            Team = "Pistons",
                            ThreePAr = 0.39400000000000002,
                            WinRecord = 41
                        },
                        new
                        {
                            TeamHistoryId = 17,
                            DEFGPct = 0.51000000000000001,
                            DRB = 0.0,
                            DRTg = 107.59999999999999,
                            FTr = 0.247,
                            LossRecord = 43,
                            MOV = -0.23000000000000001,
                            NRTg = 0.0,
                            OEFGPct = 0.51500000000000001,
                            ORB = 24.800000000000001,
                            ORTg = 107.3,
                            SOS = -0.22,
                            Season = "2018-2019",
                            Team = "Heat",
                            ThreePAr = 0.36799999999999999,
                            WinRecord = 39
                        },
                        new
                        {
                            TeamHistoryId = 18,
                            DEFGPct = 0.53300000000000003,
                            DRB = 0.0,
                            DRTg = 111.5,
                            FTr = 0.24399999999999999,
                            LossRecord = 43,
                            MOV = -1.1200000000000001,
                            NRTg = 0.0,
                            OEFGPct = 0.52400000000000002,
                            ORB = 23.100000000000001,
                            ORTg = 110.40000000000001,
                            SOS = 0.31,
                            Season = "2018-2019",
                            Team = "Kings",
                            ThreePAr = 0.32100000000000001,
                            WinRecord = 39
                        },
                        new
                        {
                            TeamHistoryId = 19,
                            DEFGPct = 0.53800000000000003,
                            DRB = 0.0,
                            DRTg = 112.5,
                            FTr = 0.25700000000000001,
                            LossRecord = 43,
                            MOV = -1.1000000000000001,
                            NRTg = 0.0,
                            OEFGPct = 0.51400000000000001,
                            ORB = 21.699999999999999,
                            ORTg = 111.40000000000001,
                            SOS = -0.22,
                            Season = "2018-2019",
                            Team = "Hornets",
                            ThreePAr = 0.378,
                            WinRecord = 39
                        },
                        new
                        {
                            TeamHistoryId = 20,
                            DEFGPct = 0.53200000000000003,
                            DRB = 0.0,
                            DRTg = 112.59999999999999,
                            FTr = 0.254,
                            LossRecord = 49,
                            MOV = -1.3300000000000001,
                            NRTg = 0.0,
                            OEFGPct = 0.52900000000000003,
                            ORB = 24.100000000000001,
                            ORTg = 111.40000000000001,
                            SOS = 0.23000000000000001,
                            Season = "2018-2019",
                            Team = "Pelicans",
                            ThreePAr = 0.32400000000000001,
                            WinRecord = 33
                        },
                        new
                        {
                            TeamHistoryId = 21,
                            DEFGPct = 0.52200000000000002,
                            DRB = 0.0,
                            DRTg = 110.7,
                            FTr = 0.29099999999999998,
                            LossRecord = 49,
                            MOV = -1.28,
                            NRTg = 0.0,
                            OEFGPct = 0.51900000000000002,
                            ORB = 22.699999999999999,
                            ORTg = 109.40000000000001,
                            SOS = 0.41999999999999998,
                            Season = "2018-2019",
                            Team = "Mavericks",
                            ThreePAr = 0.42199999999999999,
                            WinRecord = 33
                        },
                        new
                        {
                            TeamHistoryId = 22,
                            DEFGPct = 0.53800000000000003,
                            DRB = 0.0,
                            DRTg = 112.90000000000001,
                            FTr = 0.26700000000000002,
                            LossRecord = 46,
                            MOV = -1.5,
                            NRTg = 0.0,
                            OEFGPct = 0.51100000000000001,
                            ORB = 24.600000000000001,
                            ORTg = 111.40000000000001,
                            SOS = 0.47999999999999998,
                            Season = "2018-2019",
                            Team = "Timberwolves",
                            ThreePAr = 0.315,
                            WinRecord = 36
                        },
                        new
                        {
                            TeamHistoryId = 23,
                            DEFGPct = 0.51600000000000001,
                            DRB = 0.0,
                            DRTg = 109.5,
                            FTr = 0.25700000000000001,
                            LossRecord = 45,
                            MOV = -1.72,
                            NRTg = 0.0,
                            OEFGPct = 0.52700000000000002,
                            ORB = 22.199999999999999,
                            ORTg = 107.8,
                            SOS = 0.39000000000000001,
                            Season = "2018-2019",
                            Team = "Lakers",
                            ThreePAr = 0.34200000000000003,
                            WinRecord = 37
                        },
                        new
                        {
                            TeamHistoryId = 24,
                            DEFGPct = 0.52100000000000002,
                            DRB = 0.0,
                            DRTg = 108.8,
                            FTr = 0.27200000000000002,
                            LossRecord = 49,
                            MOV = -2.6000000000000001,
                            NRTg = 0.0,
                            OEFGPct = 0.50800000000000001,
                            ORB = 20.0,
                            ORTg = 106.09999999999999,
                            SOS = 0.51000000000000001,
                            Season = "2018-2019",
                            Team = "Grizzlies",
                            ThreePAr = 0.34200000000000003,
                            WinRecord = 33
                        },
                        new
                        {
                            TeamHistoryId = 25,
                            DEFGPct = 0.54600000000000004,
                            DRB = 0.0,
                            DRTg = 113.90000000000001,
                            FTr = 0.26600000000000001,
                            LossRecord = 50,
                            MOV = -2.8999999999999999,
                            NRTg = 0.0,
                            OEFGPct = 0.53100000000000003,
                            ORB = 21.300000000000001,
                            ORTg = 111.09999999999999,
                            SOS = -0.40000000000000002,
                            Season = "2018-2019",
                            Team = "Wizards",
                            ThreePAr = 0.37,
                            WinRecord = 32
                        },
                        new
                        {
                            TeamHistoryId = 26,
                            DEFGPct = 0.54100000000000004,
                            DRB = 0.0,
                            DRTg = 113.90000000000001,
                            FTr = 0.255,
                            LossRecord = 53,
                            MOV = -6.0199999999999996,
                            NRTg = 0.0,
                            OEFGPct = 0.52200000000000002,
                            ORB = 24.699999999999999,
                            ORTg = 108.09999999999999,
                            SOS = -0.040000000000000001,
                            Season = "2018-2019",
                            Team = "Hawks",
                            ThreePAr = 0.40300000000000002,
                            WinRecord = 29
                        },
                        new
                        {
                            TeamHistoryId = 27,
                            DEFGPct = 0.54100000000000004,
                            DRB = 0.0,
                            DRTg = 113.2,
                            FTr = 0.23499999999999999,
                            LossRecord = 60,
                            MOV = -8.4100000000000001,
                            NRTg = 0.0,
                            OEFGPct = 0.505,
                            ORB = 19.399999999999999,
                            ORTg = 104.8,
                            SOS = 0.10000000000000001,
                            Season = "2018-2019",
                            Team = "Bulls",
                            ThreePAr = 0.29499999999999998,
                            WinRecord = 22
                        },
                        new
                        {
                            TeamHistoryId = 28,
                            DEFGPct = 0.53300000000000003,
                            DRB = 0.0,
                            DRTg = 113.7,
                            FTr = 0.27000000000000002,
                            LossRecord = 65,
                            MOV = -9.2100000000000009,
                            NRTg = 0.0,
                            OEFGPct = 0.48999999999999999,
                            ORB = 22.100000000000001,
                            ORTg = 104.5,
                            SOS = 0.28000000000000003,
                            Season = "2018-2019",
                            Team = "Knicks",
                            ThreePAr = 0.33400000000000002,
                            WinRecord = 17
                        },
                        new
                        {
                            TeamHistoryId = 29,
                            DEFGPct = 0.54500000000000004,
                            DRB = 0.0,
                            DRTg = 115.09999999999999,
                            FTr = 0.25900000000000001,
                            LossRecord = 63,
                            MOV = -9.3399999999999999,
                            NRTg = 0.0,
                            OEFGPct = 0.51400000000000001,
                            ORB = 20.5,
                            ORTg = 105.90000000000001,
                            SOS = 0.72999999999999998,
                            Season = "2018-2019",
                            Team = "Suns",
                            ThreePAr = 0.33500000000000002,
                            WinRecord = 19
                        },
                        new
                        {
                            TeamHistoryId = 30,
                            DEFGPct = 0.56399999999999995,
                            DRB = 0.0,
                            DRTg = 117.59999999999999,
                            FTr = 0.23599999999999999,
                            LossRecord = 63,
                            MOV = -9.6099999999999994,
                            NRTg = 0.0,
                            OEFGPct = 0.503,
                            ORB = 23.699999999999999,
                            ORTg = 107.7,
                            SOS = 0.22,
                            Season = "2018-2019",
                            Team = "Cavaliers",
                            ThreePAr = 0.33200000000000002,
                            WinRecord = 19
                        },
                        new
                        {
                            TeamHistoryId = 31,
                            DEFGPct = 0.48899999999999999,
                            DRB = 0.0,
                            DRTg = 102.90000000000001,
                            FTr = 0.27100000000000002,
                            LossRecord = 17,
                            MOV = 10.08,
                            NRTg = 0.0,
                            OEFGPct = 0.55200000000000005,
                            ORB = 20.699999999999999,
                            ORTg = 112.40000000000001,
                            SOS = -0.67000000000000004,
                            Season = "2019-2020",
                            Team = "Bucks",
                            ThreePAr = 0.42799999999999999,
                            WinRecord = 56
                        },
                        new
                        {
                            TeamHistoryId = 32,
                            DEFGPct = 0.50900000000000001,
                            DRB = 0.0,
                            DRTg = 107.0,
                            FTr = 0.25900000000000001,
                            LossRecord = 24,
                            MOV = 6.3099999999999996,
                            NRTg = 0.0,
                            OEFGPct = 0.53100000000000003,
                            ORB = 23.899999999999999,
                            ORTg = 113.3,
                            SOS = -0.46999999999999997,
                            Season = "2019-2020",
                            Team = "Celtics",
                            ThreePAr = 0.38600000000000001,
                            WinRecord = 48
                        },
                        new
                        {
                            TeamHistoryId = 33,
                            DEFGPct = 0.50600000000000001,
                            DRB = 0.0,
                            DRTg = 107.59999999999999,
                            FTr = 0.29499999999999998,
                            LossRecord = 23,
                            MOV = 6.4400000000000004,
                            NRTg = 0.0,
                            OEFGPct = 0.53500000000000003,
                            ORB = 23.5,
                            ORTg = 113.90000000000001,
                            SOS = 0.20999999999999999,
                            Season = "2019-2020",
                            Team = "Clippers",
                            ThreePAr = 0.375,
                            WinRecord = 49
                        },
                        new
                        {
                            TeamHistoryId = 34,
                            DEFGPct = 0.502,
                            DRB = 0.0,
                            DRTg = 105.0,
                            FTr = 0.26400000000000001,
                            LossRecord = 19,
                            MOV = 6.2400000000000002,
                            NRTg = 0.0,
                            OEFGPct = 0.53600000000000003,
                            ORB = 21.300000000000001,
                            ORTg = 111.09999999999999,
                            SOS = -0.26000000000000001,
                            Season = "2019-2020",
                            Team = "Raptors",
                            ThreePAr = 0.42099999999999999,
                            WinRecord = 53
                        },
                        new
                        {
                            TeamHistoryId = 35,
                            DEFGPct = 0.51500000000000001,
                            DRB = 0.0,
                            DRTg = 106.3,
                            FTr = 0.27600000000000002,
                            LossRecord = 19,
                            MOV = 5.79,
                            NRTg = 0.0,
                            OEFGPct = 0.54200000000000004,
                            ORB = 24.5,
                            ORTg = 112.0,
                            SOS = 0.48999999999999999,
                            Season = "2019-2020",
                            Team = "Lakers",
                            ThreePAr = 0.35799999999999998,
                            WinRecord = 52
                        },
                        new
                        {
                            TeamHistoryId = 36,
                            DEFGPct = 0.52500000000000002,
                            DRB = 0.0,
                            DRTg = 111.7,
                            FTr = 0.26400000000000001,
                            LossRecord = 32,
                            MOV = 4.9500000000000002,
                            NRTg = 0.0,
                            OEFGPct = 0.54500000000000004,
                            ORB = 23.199999999999999,
                            ORTg = 116.7,
                            SOS = -0.070000000000000007,
                            Season = "2019-2020",
                            Team = "Mavericks",
                            ThreePAr = 0.45700000000000002,
                            WinRecord = 43
                        },
                        new
                        {
                            TeamHistoryId = 37,
                            DEFGPct = 0.52300000000000002,
                            DRB = 0.0,
                            DRTg = 109.5,
                            FTr = 0.29899999999999999,
                            LossRecord = 29,
                            MOV = 2.9500000000000002,
                            NRTg = 0.0,
                            OEFGPct = 0.54700000000000004,
                            ORB = 20.300000000000001,
                            ORTg = 112.5,
                            SOS = -0.34999999999999998,
                            Season = "2019-2020",
                            Team = "Heat",
                            ThreePAr = 0.41899999999999998,
                            WinRecord = 44
                        },
                        new
                        {
                            TeamHistoryId = 38,
                            DEFGPct = 0.52900000000000003,
                            DRB = 0.0,
                            DRTg = 110.09999999999999,
                            FTr = 0.28799999999999998,
                            LossRecord = 28,
                            MOV = 2.96,
                            NRTg = 0.0,
                            OEFGPct = 0.53700000000000003,
                            ORB = 21.0,
                            ORTg = 112.90000000000001,
                            SOS = 0.17000000000000001,
                            Season = "2019-2020",
                            Team = "Rockets",
                            ThreePAr = 0.501,
                            WinRecord = 44
                        },
                        new
                        {
                            TeamHistoryId = 39,
                            DEFGPct = 0.51800000000000002,
                            DRB = 0.0,
                            DRTg = 109.90000000000001,
                            FTr = 0.26800000000000002,
                            LossRecord = 28,
                            MOV = 2.4700000000000002,
                            NRTg = 0.0,
                            OEFGPct = 0.54900000000000004,
                            ORB = 21.600000000000001,
                            ORTg = 112.3,
                            SOS = 0.050000000000000003,
                            Season = "2019-2020",
                            Team = "Jazz",
                            ThreePAr = 0.41399999999999998,
                            WinRecord = 44
                        },
                        new
                        {
                            TeamHistoryId = 40,
                            DEFGPct = 0.52300000000000002,
                            DRB = 0.0,
                            DRTg = 109.0,
                            FTr = 0.255,
                            LossRecord = 30,
                            MOV = 2.3799999999999999,
                            NRTg = 0.0,
                            OEFGPct = 0.53400000000000003,
                            ORB = 23.899999999999999,
                            ORTg = 111.3,
                            SOS = -0.13,
                            Season = "2019-2020",
                            Team = "76ers",
                            ThreePAr = 0.35999999999999999,
                            WinRecord = 43
                        },
                        new
                        {
                            TeamHistoryId = 41,
                            DEFGPct = 0.53300000000000003,
                            DRB = 0.0,
                            DRTg = 111.0,
                            FTr = 0.23499999999999999,
                            LossRecord = 27,
                            MOV = 2.1099999999999999,
                            NRTg = 0.0,
                            OEFGPct = 0.53500000000000003,
                            ORB = 24.800000000000001,
                            ORTg = 113.09999999999999,
                            SOS = 0.23999999999999999,
                            Season = "2019-2020",
                            Team = "Nuggets",
                            ThreePAr = 0.34399999999999997,
                            WinRecord = 46
                        },
                        new
                        {
                            TeamHistoryId = 42,
                            DEFGPct = 0.51100000000000001,
                            DRB = 0.0,
                            DRTg = 108.0,
                            FTr = 0.216,
                            LossRecord = 28,
                            MOV = 1.96,
                            NRTg = 0.0,
                            OEFGPct = 0.53400000000000003,
                            ORB = 20.0,
                            ORTg = 110.0,
                            SOS = -0.33000000000000002,
                            Season = "2019-2020",
                            Team = "Pacers",
                            ThreePAr = 0.317,
                            WinRecord = 45
                        },
                        new
                        {
                            TeamHistoryId = 43,
                            DEFGPct = 0.51800000000000002,
                            DRB = 0.0,
                            DRTg = 108.8,
                            FTr = 0.28999999999999998,
                            LossRecord = 28,
                            MOV = 1.99,
                            NRTg = 0.0,
                            OEFGPct = 0.53000000000000003,
                            ORB = 19.300000000000001,
                            ORTg = 110.8,
                            SOS = 0.34000000000000002,
                            Season = "2019-2020",
                            Team = "Thuder",
                            ThreePAr = 0.35299999999999998,
                            WinRecord = 44
                        },
                        new
                        {
                            TeamHistoryId = 44,
                            DEFGPct = 0.53900000000000003,
                            DRB = 0.0,
                            DRTg = 111.40000000000001,
                            FTr = 0.27100000000000002,
                            LossRecord = 39,
                            MOV = 0.22,
                            NRTg = 0.0,
                            OEFGPct = 0.53200000000000003,
                            ORB = 22.199999999999999,
                            ORTg = 111.7,
                            SOS = 0.34999999999999998,
                            Season = "2019-2020",
                            Team = "Suns",
                            ThreePAr = 0.36099999999999999,
                            WinRecord = 34
                        },
                        new
                        {
                            TeamHistoryId = 45,
                            DEFGPct = 0.51100000000000001,
                            DRB = 0.0,
                            DRTg = 109.5,
                            FTr = 0.26700000000000002,
                            LossRecord = 37,
                            MOV = -0.56999999999999995,
                            NRTg = 0.0,
                            OEFGPct = 0.52000000000000002,
                            ORB = 23.199999999999999,
                            ORTg = 108.90000000000001,
                            SOS = -0.44,
                            Season = "2019-2020",
                            Team = "Nets",
                            ThreePAr = 0.42299999999999999,
                            WinRecord = 35
                        },
                        new
                        {
                            TeamHistoryId = 46,
                            DEFGPct = 0.53500000000000003,
                            DRB = 0.0,
                            DRTg = 109.5,
                            FTr = 0.25600000000000001,
                            LossRecord = 40,
                            MOV = -1.01,
                            NRTg = 0.0,
                            OEFGPct = 0.50600000000000001,
                            ORB = 22.300000000000001,
                            ORTg = 108.5,
                            SOS = 0.089999999999999997,
                            Season = "2019-2020",
                            Team = "Magic",
                            ThreePAr = 0.36399999999999999,
                            WinRecord = 33
                        },
                        new
                        {
                            TeamHistoryId = 47,
                            DEFGPct = 0.54200000000000004,
                            DRB = 0.0,
                            DRTg = 113.5,
                            FTr = 0.26200000000000001,
                            LossRecord = 39,
                            MOV = -1.1100000000000001,
                            NRTg = 0.0,
                            OEFGPct = 0.53100000000000003,
                            ORB = 20.100000000000001,
                            ORTg = 112.40000000000001,
                            SOS = 0.46000000000000002,
                            Season = "2019-2020",
                            Team = "Spurs",
                            ThreePAr = 0.318,
                            WinRecord = 32
                        },
                        new
                        {
                            TeamHistoryId = 48,
                            DEFGPct = 0.52100000000000002,
                            DRB = 0.0,
                            DRTg = 110.3,
                            FTr = 0.23999999999999999,
                            LossRecord = 39,
                            MOV = -1.0700000000000001,
                            NRTg = 0.0,
                            OEFGPct = 0.52800000000000002,
                            ORB = 23.0,
                            ORTg = 109.2,
                            SOS = 0.16,
                            Season = "2019-2020",
                            Team = "Grizzlies",
                            ThreePAr = 0.34599999999999997,
                            WinRecord = 34
                        },
                        new
                        {
                            TeamHistoryId = 49,
                            DEFGPct = 0.53000000000000003,
                            DRB = 0.0,
                            DRTg = 114.8,
                            FTr = 0.24199999999999999,
                            LossRecord = 39,
                            MOV = -1.1499999999999999,
                            NRTg = 0.0,
                            OEFGPct = 0.53300000000000003,
                            ORB = 22.399999999999999,
                            ORTg = 113.7,
                            SOS = 0.54000000000000004,
                            Season = "2019-2020",
                            Team = "Trail Blazers",
                            ThreePAr = 0.374,
                            WinRecord = 35
                        },
                        new
                        {
                            TeamHistoryId = 50,
                            DEFGPct = 0.53200000000000003,
                            DRB = 0.0,
                            DRTg = 111.90000000000001,
                            FTr = 0.25600000000000001,
                            LossRecord = 42,
                            MOV = -1.29,
                            NRTg = 0.0,
                            OEFGPct = 0.53900000000000003,
                            ORB = 24.199999999999999,
                            ORTg = 110.7,
                            SOS = 0.73999999999999999,
                            Season = "2019-2020",
                            Team = "Pelicans",
                            ThreePAr = 0.40300000000000002,
                            WinRecord = 30
                        },
                        new
                        {
                            TeamHistoryId = 51,
                            DEFGPct = 0.54300000000000004,
                            DRB = 0.0,
                            DRTg = 112.2,
                            FTr = 0.23000000000000001,
                            LossRecord = 41,
                            MOV = -2.04,
                            NRTg = 0.0,
                            OEFGPct = 0.53400000000000003,
                            ORB = 21.899999999999999,
                            ORTg = 110.2,
                            SOS = 0.46000000000000002,
                            Season = "2019-2020",
                            Team = "Kings",
                            ThreePAr = 0.39500000000000002,
                            WinRecord = 31
                        },
                        new
                        {
                            TeamHistoryId = 52,
                            DEFGPct = 0.54600000000000004,
                            DRB = 0.0,
                            DRTg = 109.8,
                            FTr = 0.23100000000000001,
                            LossRecord = 43,
                            MOV = -3.0800000000000001,
                            NRTg = 0.0,
                            OEFGPct = 0.51500000000000001,
                            ORB = 22.800000000000001,
                            ORTg = 106.7,
                            SOS = -0.93000000000000005,
                            Season = "2019-2020",
                            Team = "Bulls",
                            ThreePAr = 0.39600000000000002,
                            WinRecord = 22
                        },
                        new
                        {
                            TeamHistoryId = 53,
                            DEFGPct = 0.54100000000000004,
                            DRB = 0.0,
                            DRTg = 112.7,
                            FTr = 0.26100000000000001,
                            LossRecord = 46,
                            MOV = -3.5600000000000001,
                            NRTg = 0.0,
                            OEFGPct = 0.52900000000000003,
                            ORB = 22.600000000000001,
                            ORTg = 109.0,
                            SOS = -0.81999999999999995,
                            Season = "2019-2020",
                            Team = "Pistons",
                            ThreePAr = 0.38100000000000001,
                            WinRecord = 20
                        },
                        new
                        {
                            TeamHistoryId = 54,
                            DEFGPct = 0.54100000000000004,
                            DRB = 0.0,
                            DRTg = 112.2,
                            FTr = 0.27700000000000002,
                            LossRecord = 45,
                            MOV = -4.2999999999999998,
                            NRTg = 0.0,
                            OEFGPct = 0.51400000000000001,
                            ORB = 22.100000000000001,
                            ORTg = 108.09999999999999,
                            SOS = 0.28000000000000003,
                            Season = "2019-2020",
                            Team = "Timberwolves",
                            ThreePAr = 0.433,
                            WinRecord = 19
                        },
                        new
                        {
                            TeamHistoryId = 55,
                            DEFGPct = 0.55800000000000005,
                            DRB = 0.0,
                            DRTg = 115.5,
                            FTr = 0.27000000000000002,
                            LossRecord = 47,
                            MOV = -4.6699999999999999,
                            NRTg = 0.0,
                            OEFGPct = 0.52300000000000002,
                            ORB = 22.199999999999999,
                            ORTg = 110.90000000000001,
                            SOS = -0.56999999999999995,
                            Season = "2019-2020",
                            Team = "Wizards",
                            ThreePAr = 0.35799999999999998,
                            WinRecord = 25
                        },
                        new
                        {
                            TeamHistoryId = 56,
                            DEFGPct = 0.54100000000000004,
                            DRB = 0.0,
                            DRTg = 113.0,
                            FTr = 0.26300000000000001,
                            LossRecord = 45,
                            MOV = -6.4500000000000002,
                            NRTg = 0.0,
                            OEFGPct = 0.501,
                            ORB = 25.800000000000001,
                            ORTg = 106.5,
                            SOS = -0.26000000000000001,
                            Season = "2019-2020",
                            Team = "Knicks",
                            ThreePAr = 0.318,
                            WinRecord = 21
                        },
                        new
                        {
                            TeamHistoryId = 57,
                            DEFGPct = 0.54600000000000004,
                            DRB = 0.0,
                            DRTg = 113.3,
                            FTr = 0.252,
                            LossRecord = 42,
                            MOV = -6.75,
                            NRTg = 0.0,
                            OEFGPct = 0.504,
                            ORB = 23.899999999999999,
                            ORTg = 106.3,
                            SOS = -0.28000000000000003,
                            Season = "2019-2020",
                            Team = "Hornets",
                            ThreePAr = 0.39900000000000002,
                            WinRecord = 23
                        },
                        new
                        {
                            TeamHistoryId = 58,
                            DEFGPct = 0.54300000000000004,
                            DRB = 0.0,
                            DRTg = 114.8,
                            FTr = 0.25800000000000001,
                            LossRecord = 47,
                            MOV = -7.9699999999999998,
                            NRTg = 0.0,
                            OEFGPct = 0.51500000000000001,
                            ORB = 21.600000000000001,
                            ORTg = 107.2,
                            SOS = 0.27000000000000002,
                            Season = "2019-2020",
                            Team = "Hawks",
                            ThreePAr = 0.39800000000000002,
                            WinRecord = 20
                        },
                        new
                        {
                            TeamHistoryId = 59,
                            DEFGPct = 0.56000000000000005,
                            DRB = 0.0,
                            DRTg = 115.40000000000001,
                            FTr = 0.22700000000000001,
                            LossRecord = 46,
                            MOV = -7.8899999999999997,
                            NRTg = 0.0,
                            OEFGPct = 0.52200000000000002,
                            ORB = 24.600000000000001,
                            ORTg = 107.5,
                            SOS = 0.12,
                            Season = "2019-2020",
                            Team = "Cavaliers",
                            ThreePAr = 0.36199999999999999,
                            WinRecord = 19
                        },
                        new
                        {
                            TeamHistoryId = 60,
                            DEFGPct = 0.55300000000000005,
                            DRB = 0.0,
                            DRTg = 113.8,
                            FTr = 0.26400000000000001,
                            LossRecord = 50,
                            MOV = -8.7100000000000009,
                            NRTg = 0.0,
                            OEFGPct = 0.497,
                            ORB = 21.5,
                            ORTg = 105.2,
                            SOS = 0.58999999999999997,
                            Season = "2019-2020",
                            Team = "Warriors",
                            ThreePAr = 0.35499999999999998,
                            WinRecord = 15
                        },
                        new
                        {
                            TeamHistoryId = 61,
                            DEFGPct = 0.50700000000000001,
                            DRB = 0.0,
                            DRTg = 108.3,
                            FTr = 0.24399999999999999,
                            LossRecord = 20,
                            MOV = 9.25,
                            NRTg = 0.0,
                            OEFGPct = 0.56299999999999994,
                            ORB = 24.5,
                            ORTg = 117.59999999999999,
                            SOS = -0.28999999999999998,
                            Season = "2020-2021",
                            Team = "Jazz",
                            ThreePAr = 0.48799999999999999,
                            WinRecord = 52
                        },
                        new
                        {
                            TeamHistoryId = 62,
                            DEFGPct = 0.53100000000000003,
                            DRB = 0.0,
                            DRTg = 111.2,
                            FTr = 0.222,
                            LossRecord = 25,
                            MOV = 6.1799999999999997,
                            NRTg = 0.0,
                            OEFGPct = 0.56399999999999995,
                            ORB = 22.699999999999999,
                            ORTg = 117.59999999999999,
                            SOS = -0.16,
                            Season = "2020-2021",
                            Team = "Clippers",
                            ThreePAr = 0.40000000000000002,
                            WinRecord = 47
                        },
                        new
                        {
                            TeamHistoryId = 63,
                            DEFGPct = 0.53400000000000003,
                            DRB = 0.0,
                            DRTg = 111.3,
                            FTr = 0.21199999999999999,
                            LossRecord = 21,
                            MOV = 5.8200000000000003,
                            NRTg = 0.0,
                            OEFGPct = 0.56399999999999995,
                            ORB = 20.800000000000001,
                            ORTg = 117.2,
                            SOS = -0.14999999999999999,
                            Season = "2020-2021",
                            Team = "Suns",
                            ThreePAr = 0.39200000000000002,
                            WinRecord = 51
                        },
                        new
                        {
                            TeamHistoryId = 64,
                            DEFGPct = 0.53600000000000003,
                            DRB = 0.0,
                            DRTg = 111.40000000000001,
                            FTr = 0.23300000000000001,
                            LossRecord = 26,
                            MOV = 5.8899999999999997,
                            NRTg = 0.0,
                            OEFGPct = 0.56599999999999995,
                            ORB = 23.300000000000001,
                            ORTg = 117.2,
                            SOS = -0.32000000000000001,
                            Season = "2020-2021",
                            Team = "Bucks",
                            ThreePAr = 0.40400000000000003,
                            WinRecord = 46
                        },
                        new
                        {
                            TeamHistoryId = 65,
                            DEFGPct = 0.52100000000000002,
                            DRB = 0.0,
                            DRTg = 107.59999999999999,
                            FTr = 0.29299999999999998,
                            LossRecord = 23,
                            MOV = 5.5800000000000001,
                            NRTg = 0.0,
                            OEFGPct = 0.54100000000000004,
                            ORB = 23.199999999999999,
                            ORTg = 113.2,
                            SOS = -0.31,
                            Season = "2020-2021",
                            Team = "76ers",
                            ThreePAr = 0.34699999999999998,
                            WinRecord = 49
                        },
                        new
                        {
                            TeamHistoryId = 66,
                            DEFGPct = 0.54500000000000004,
                            DRB = 0.0,
                            DRTg = 112.09999999999999,
                            FTr = 0.219,
                            LossRecord = 25,
                            MOV = 4.9299999999999997,
                            NRTg = 0.0,
                            OEFGPct = 0.55700000000000005,
                            ORB = 24.699999999999999,
                            ORTg = 117.09999999999999,
                            SOS = -0.11,
                            Season = "2020-2021",
                            Team = "Nuggets",
                            ThreePAr = 0.38300000000000001,
                            WinRecord = 47
                        },
                        new
                        {
                            TeamHistoryId = 67,
                            DEFGPct = 0.53100000000000003,
                            DRB = 0.0,
                            DRTg = 113.8,
                            FTr = 0.25800000000000001,
                            LossRecord = 24,
                            MOV = 4.5,
                            NRTg = 0.0,
                            OEFGPct = 0.57499999999999996,
                            ORB = 21.399999999999999,
                            ORTg = 118.3,
                            SOS = -0.27000000000000002,
                            Season = "2020-2021",
                            Team = "Nets",
                            ThreePAr = 0.41299999999999998,
                            WinRecord = 48
                        },
                        new
                        {
                            TeamHistoryId = 68,
                            DEFGPct = 0.52600000000000002,
                            DRB = 0.0,
                            DRTg = 107.09999999999999,
                            FTr = 0.27100000000000002,
                            LossRecord = 30,
                            MOV = 2.79,
                            NRTg = 0.0,
                            OEFGPct = 0.53600000000000003,
                            ORB = 22.5,
                            ORTg = 109.90000000000001,
                            SOS = -0.029999999999999999,
                            Season = "2020-2021",
                            Team = "Lakers",
                            ThreePAr = 0.36299999999999999,
                            WinRecord = 42
                        },
                        new
                        {
                            TeamHistoryId = 69,
                            DEFGPct = 0.53400000000000003,
                            DRB = 0.0,
                            DRTg = 113.0,
                            FTr = 0.24199999999999999,
                            LossRecord = 30,
                            MOV = 2.2599999999999998,
                            NRTg = 0.0,
                            OEFGPct = 0.55000000000000004,
                            ORB = 21.100000000000001,
                            ORTg = 115.40000000000001,
                            SOS = -0.01,
                            Season = "2020-2021",
                            Team = "Mavericks",
                            ThreePAr = 0.436,
                            WinRecord = 42
                        },
                        new
                        {
                            TeamHistoryId = 70,
                            DEFGPct = 0.50900000000000001,
                            DRB = 0.0,
                            DRTg = 108.2,
                            FTr = 0.24199999999999999,
                            LossRecord = 31,
                            MOV = 2.3100000000000001,
                            NRTg = 0.0,
                            OEFGPct = 0.52400000000000002,
                            ORB = 21.899999999999999,
                            ORTg = 110.59999999999999,
                            SOS = -0.17999999999999999,
                            Season = "2020-2021",
                            Team = "Knicks",
                            ThreePAr = 0.34699999999999998,
                            WinRecord = 41
                        },
                        new
                        {
                            TeamHistoryId = 71,
                            DEFGPct = 0.53000000000000003,
                            DRB = 0.0,
                            DRTg = 113.3,
                            FTr = 0.27800000000000002,
                            LossRecord = 31,
                            MOV = 2.3199999999999998,
                            NRTg = 0.0,
                            OEFGPct = 0.53900000000000003,
                            ORB = 24.399999999999999,
                            ORTg = 115.7,
                            SOS = -0.17999999999999999,
                            Season = "2020-2021",
                            Team = "Hawks",
                            ThreePAr = 0.38200000000000001,
                            WinRecord = 41
                        },
                        new
                        {
                            TeamHistoryId = 72,
                            DEFGPct = 0.54600000000000004,
                            DRB = 0.0,
                            DRTg = 116.0,
                            FTr = 0.23799999999999999,
                            LossRecord = 30,
                            MOV = 1.79,
                            NRTg = 0.0,
                            OEFGPct = 0.54000000000000004,
                            ORB = 23.0,
                            ORTg = 117.8,
                            SOS = 0.01,
                            Season = "2020-2021",
                            Team = "Trail Blazers",
                            ThreePAr = 0.44800000000000001,
                            WinRecord = 42
                        },
                        new
                        {
                            TeamHistoryId = 73,
                            DEFGPct = 0.53900000000000003,
                            DRB = 0.0,
                            DRTg = 112.5,
                            FTr = 0.23400000000000001,
                            LossRecord = 36,
                            MOV = 1.46,
                            NRTg = 0.0,
                            OEFGPct = 0.54300000000000004,
                            ORB = 24.300000000000001,
                            ORTg = 114.0,
                            SOS = -0.14000000000000001,
                            Season = "2020-2021",
                            Team = "Celtics",
                            ThreePAr = 0.40899999999999997,
                            WinRecord = 36
                        },
                        new
                        {
                            TeamHistoryId = 74,
                            DEFGPct = 0.52200000000000002,
                            DRB = 0.0,
                            DRTg = 110.09999999999999,
                            FTr = 0.23899999999999999,
                            LossRecord = 33,
                            MOV = 1.0600000000000001,
                            NRTg = 0.0,
                            OEFGPct = 0.55100000000000005,
                            ORB = 17.899999999999999,
                            ORTg = 111.09999999999999,
                            SOS = 0.040000000000000001,
                            Season = "2020-2021",
                            Team = "Warriors",
                            ThreePAr = 0.439,
                            WinRecord = 39
                        },
                        new
                        {
                            TeamHistoryId = 75,
                            DEFGPct = 0.53500000000000003,
                            DRB = 0.0,
                            DRTg = 111.0,
                            FTr = 0.23200000000000001,
                            LossRecord = 34,
                            MOV = 1.03,
                            NRTg = 0.0,
                            OEFGPct = 0.52800000000000002,
                            ORB = 24.199999999999999,
                            ORTg = 112.0,
                            SOS = 0.040000000000000001,
                            Season = "2020-2021",
                            Team = "Grizzlies",
                            ThreePAr = 0.34200000000000003,
                            WinRecord = 38
                        },
                        new
                        {
                            TeamHistoryId = 76,
                            DEFGPct = 0.54200000000000004,
                            DRB = 0.0,
                            DRTg = 111.2,
                            FTr = 0.252,
                            LossRecord = 32,
                            MOV = 0.029999999999999999,
                            NRTg = 0.0,
                            OEFGPct = 0.54600000000000004,
                            ORB = 19.399999999999999,
                            ORTg = 111.2,
                            SOS = -0.089999999999999997,
                            Season = "2020-2021",
                            Team = "Heat",
                            ThreePAr = 0.432,
                            WinRecord = 40
                        },
                        new
                        {
                            TeamHistoryId = 77,
                            DEFGPct = 0.53100000000000003,
                            DRB = 0.0,
                            DRTg = 112.40000000000001,
                            FTr = 0.22700000000000001,
                            LossRecord = 38,
                            MOV = -0.040000000000000001,
                            NRTg = 0.0,
                            OEFGPct = 0.54200000000000004,
                            ORB = 20.199999999999999,
                            ORTg = 112.40000000000001,
                            SOS = -0.080000000000000002,
                            Season = "2020-2021",
                            Team = "Pacers",
                            ThreePAr = 0.372,
                            WinRecord = 34
                        },
                        new
                        {
                            TeamHistoryId = 78,
                            DEFGPct = 0.55000000000000004,
                            DRB = 0.0,
                            DRTg = 113.8,
                            FTr = 0.29299999999999998,
                            LossRecord = 41,
                            MOV = -0.28999999999999998,
                            NRTg = 0.0,
                            OEFGPct = 0.53700000000000003,
                            ORB = 26.300000000000001,
                            ORTg = 113.5,
                            SOS = 0.10000000000000001,
                            Season = "2020-2021",
                            Team = "Pelicans",
                            ThreePAr = 0.34200000000000003,
                            WinRecord = 31
                        },
                        new
                        {
                            TeamHistoryId = 79,
                            DEFGPct = 0.54300000000000004,
                            DRB = 0.0,
                            DRTg = 112.5,
                            FTr = 0.24099999999999999,
                            LossRecord = 45,
                            MOV = -0.46999999999999997,
                            NRTg = 0.0,
                            OEFGPct = 0.52900000000000003,
                            ORB = 20.800000000000001,
                            ORTg = 112.0,
                            SOS = -0.070000000000000007,
                            Season = "2020-2021",
                            Team = "Raptors",
                            ThreePAr = 0.44400000000000001,
                            WinRecord = 27
                        },
                        new
                        {
                            TeamHistoryId = 80,
                            DEFGPct = 0.53800000000000003,
                            DRB = 0.0,
                            DRTg = 112.0,
                            FTr = 0.19700000000000001,
                            LossRecord = 41,
                            MOV = -0.89000000000000001,
                            NRTg = 0.0,
                            OEFGPct = 0.54700000000000004,
                            ORB = 22.300000000000001,
                            ORTg = 111.09999999999999,
                            SOS = -0.050000000000000003,
                            Season = "2020-2021",
                            Team = "Bulls",
                            ThreePAr = 0.38300000000000001,
                            WinRecord = 31
                        },
                        new
                        {
                            TeamHistoryId = 81,
                            DEFGPct = 0.54100000000000004,
                            DRB = 0.0,
                            DRTg = 112.8,
                            FTr = 0.24299999999999999,
                            LossRecord = 39,
                            MOV = -1.74,
                            NRTg = 0.0,
                            OEFGPct = 0.51700000000000002,
                            ORB = 20.0,
                            ORTg = 111.0,
                            SOS = 0.14999999999999999,
                            Season = "2020-2021",
                            Team = "Spurs",
                            ThreePAr = 0.314,
                            WinRecord = 33
                        },
                        new
                        {
                            TeamHistoryId = 82,
                            DEFGPct = 0.53900000000000003,
                            DRB = 0.0,
                            DRTg = 113.0,
                            FTr = 0.28799999999999998,
                            LossRecord = 38,
                            MOV = -1.8300000000000001,
                            NRTg = 0.0,
                            OEFGPct = 0.53100000000000003,
                            ORB = 21.300000000000001,
                            ORTg = 111.2,
                            SOS = -0.01,
                            Season = "2020-2021",
                            Team = "Wizards",
                            ThreePAr = 0.31900000000000001,
                            WinRecord = 34
                        },
                        new
                        {
                            TeamHistoryId = 83,
                            DEFGPct = 0.55000000000000004,
                            DRB = 0.0,
                            DRTg = 112.8,
                            FTr = 0.23799999999999999,
                            LossRecord = 39,
                            MOV = -1.9299999999999999,
                            NRTg = 0.0,
                            OEFGPct = 0.53200000000000003,
                            ORB = 23.5,
                            ORTg = 110.90000000000001,
                            SOS = -0.01,
                            Season = "2020-2021",
                            Team = "Hornets",
                            ThreePAr = 0.42199999999999999,
                            WinRecord = 33
                        },
                        new
                        {
                            TeamHistoryId = 84,
                            DEFGPct = 0.55700000000000005,
                            DRB = 0.0,
                            DRTg = 117.2,
                            FTr = 0.248,
                            LossRecord = 41,
                            MOV = -3.6800000000000002,
                            NRTg = 0.0,
                            OEFGPct = 0.54900000000000004,
                            ORB = 21.300000000000001,
                            ORTg = 113.59999999999999,
                            SOS = 0.23000000000000001,
                            Season = "2020-2021",
                            Team = "Kings",
                            ThreePAr = 0.376,
                            WinRecord = 31
                        },
                        new
                        {
                            TeamHistoryId = 85,
                            DEFGPct = 0.54100000000000004,
                            DRB = 0.0,
                            DRTg = 112.5,
                            FTr = 0.27300000000000002,
                            LossRecord = 52,
                            MOV = -4.4699999999999998,
                            NRTg = 0.0,
                            OEFGPct = 0.51900000000000002,
                            ORB = 21.899999999999999,
                            ORTg = 108.0,
                            SOS = 0.089999999999999997,
                            Season = "2020-2021",
                            Team = "Pistons",
                            ThreePAr = 0.38500000000000001,
                            WinRecord = 20
                        },
                        new
                        {
                            TeamHistoryId = 86,
                            DEFGPct = 0.55600000000000005,
                            DRB = 0.0,
                            DRTg = 115.0,
                            FTr = 0.254,
                            LossRecord = 49,
                            MOV = -5.5599999999999996,
                            NRTg = 0.0,
                            OEFGPct = 0.52000000000000002,
                            ORB = 22.699999999999999,
                            ORTg = 109.5,
                            SOS = 0.31,
                            Season = "2020-2021",
                            Team = "Timberwolves",
                            ThreePAr = 0.41299999999999998,
                            WinRecord = 23
                        },
                        new
                        {
                            TeamHistoryId = 87,
                            DEFGPct = 0.55500000000000005,
                            DRB = 0.0,
                            DRTg = 114.90000000000001,
                            FTr = 0.252,
                            LossRecord = 55,
                            MOV = -7.9000000000000004,
                            NRTg = 0.0,
                            OEFGPct = 0.52100000000000002,
                            ORB = 19.800000000000001,
                            ORTg = 107.09999999999999,
                            SOS = 0.40000000000000002,
                            Season = "2020-2021",
                            Team = "Rockets",
                            ThreePAr = 0.45900000000000002,
                            WinRecord = 17
                        },
                        new
                        {
                            TeamHistoryId = 88,
                            DEFGPct = 0.55600000000000005,
                            DRB = 0.0,
                            DRTg = 114.40000000000001,
                            FTr = 0.26100000000000001,
                            LossRecord = 50,
                            MOV = -8.4399999999999995,
                            NRTg = 0.0,
                            OEFGPct = 0.50800000000000001,
                            ORB = 23.600000000000001,
                            ORTg = 105.8,
                            SOS = 0.25,
                            Season = "2020-2021",
                            Team = "Cavaliers",
                            ThreePAr = 0.34699999999999998,
                            WinRecord = 22
                        },
                        new
                        {
                            TeamHistoryId = 89,
                            DEFGPct = 0.54700000000000004,
                            DRB = 0.0,
                            DRTg = 114.5,
                            FTr = 0.23999999999999999,
                            LossRecord = 51,
                            MOV = -9.3100000000000005,
                            NRTg = 0.0,
                            OEFGPct = 0.48999999999999999,
                            ORB = 21.600000000000001,
                            ORTg = 105.09999999999999,
                            SOS = 0.28999999999999998,
                            Season = "2020-2021",
                            Team = "Magic",
                            ThreePAr = 0.35599999999999998,
                            WinRecord = 21
                        },
                        new
                        {
                            TeamHistoryId = 90,
                            DEFGPct = 0.54700000000000004,
                            DRB = 0.0,
                            DRTg = 114.0,
                            FTr = 0.24199999999999999,
                            LossRecord = 50,
                            MOV = -10.640000000000001,
                            NRTg = 0.0,
                            OEFGPct = 0.50900000000000001,
                            ORB = 21.199999999999999,
                            ORTg = 103.5,
                            SOS = 0.51000000000000001,
                            Season = "2020-2021",
                            Team = "Thunder",
                            ThreePAr = 0.39900000000000002,
                            WinRecord = 22
                        });
                });

            modelBuilder.Entity("Domain.Entities.Player", b =>
                {
                    b.HasOne("Domain.Entities.Team", null)
                        .WithMany("Players")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("Domain.Entities.TeamHistory", b =>
                {
                    b.HasOne("Domain.Entities.Team", null)
                        .WithMany("TeamHistories")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("Domain.Entities.Team", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("TeamHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
