// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NBAapi.Models;

namespace NBAapi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220102025243_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("NBAapi.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Joined")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Team")
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId");

                    b.ToTable("Player");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            Joined = new DateTime(2022, 1, 1, 18, 52, 42, 618, DateTimeKind.Local).AddTicks(3950),
                            Name = "Trae Young",
                            PhotoPath = "/Photos/nba_anonymous.jpg",
                            Team = "Hawks"
                        },
                        new
                        {
                            PlayerId = 2,
                            Joined = new DateTime(2022, 1, 1, 18, 52, 42, 618, DateTimeKind.Local).AddTicks(6460),
                            Name = "Jayson Tatum",
                            PhotoPath = "/Photos/nba_anonymous.jpg",
                            Team = "Celtics"
                        },
                        new
                        {
                            PlayerId = 3,
                            Joined = new DateTime(2022, 1, 1, 18, 52, 42, 618, DateTimeKind.Local).AddTicks(7280),
                            Name = "Kevin Durant",
                            PhotoPath = "/Photos/nba_anonymous.jpg",
                            Team = "Nets"
                        },
                        new
                        {
                            PlayerId = 4,
                            Joined = new DateTime(2022, 1, 1, 18, 52, 42, 618, DateTimeKind.Local).AddTicks(7350),
                            Name = "Stephen Curry",
                            PhotoPath = "/Photos/nba_anonymous.jpg",
                            Team = "Warriors"
                        },
                        new
                        {
                            PlayerId = 5,
                            Joined = new DateTime(2022, 1, 1, 18, 52, 42, 618, DateTimeKind.Local).AddTicks(7360),
                            Name = "Zach LaVine",
                            PhotoPath = "/Photos/nba_anonymous.jpg",
                            Team = "Bulls"
                        },
                        new
                        {
                            PlayerId = 6,
                            Joined = new DateTime(2022, 1, 1, 18, 52, 42, 618, DateTimeKind.Local).AddTicks(7370),
                            Name = "LeBron James",
                            PhotoPath = "/Photos/nba_anonymous.jpg",
                            Team = "Lakers"
                        },
                        new
                        {
                            PlayerId = 7,
                            Joined = new DateTime(2022, 1, 1, 18, 52, 42, 618, DateTimeKind.Local).AddTicks(7390),
                            Name = "Julius Randle",
                            PhotoPath = "/Photos/nba_anonymous.jpg",
                            Team = "Knicks"
                        });
                });

            modelBuilder.Entity("NBAapi.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateFounded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("TEXT");

                    b.HasKey("TeamId");

                    b.ToTable("Team");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            City = "Atlanta",
                            DateFounded = new DateTime(2022, 1, 1, 18, 52, 42, 596, DateTimeKind.Local).AddTicks(6210),
                            Name = "Hawks",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 2,
                            City = "Boston",
                            DateFounded = new DateTime(2022, 1, 1, 18, 52, 42, 615, DateTimeKind.Local).AddTicks(9750),
                            Name = "Celtics",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 3,
                            City = "Brooklyn",
                            DateFounded = new DateTime(2022, 1, 1, 18, 52, 42, 616, DateTimeKind.Local).AddTicks(690),
                            Name = "Nets",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 4,
                            City = "Golden State",
                            DateFounded = new DateTime(2022, 1, 1, 18, 52, 42, 616, DateTimeKind.Local).AddTicks(760),
                            Name = "Warriors",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 5,
                            City = "Chicago",
                            DateFounded = new DateTime(2022, 1, 1, 18, 52, 42, 616, DateTimeKind.Local).AddTicks(780),
                            Name = "Bulls",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 6,
                            City = "Los Angeles",
                            DateFounded = new DateTime(2022, 1, 1, 18, 52, 42, 616, DateTimeKind.Local).AddTicks(790),
                            Name = "Lakers",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        },
                        new
                        {
                            TeamId = 7,
                            City = "New York",
                            DateFounded = new DateTime(2022, 1, 1, 18, 52, 42, 616, DateTimeKind.Local).AddTicks(800),
                            Name = "Knicks",
                            PhotoPath = "/Photos/nba_anonymous.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
